//import { nanoid } from "nanoid";

export let clothes = [
  {
    id: "1",
    name: "Classic T-Shirt",
    image: "src/assets/logo.png",
    priceCents: 1999,
    gender: "Unisex",
    category: "T-shirts",
    color: "Red",
    description:
      "A comfortable and versatile t-shirt made from breathable fabric. Designed for casual everyday wear, it is available in a vibrant red color.",
    isFavorite: false,
    rating: { stars: 4.1, reviews: 278 },
    stock: {
      S: 50,
      M: 40,
      L: 30,
      XL: 20,
    },
    fitsWith: ["Jackets", "Pants", "Shorts"],
    style: ["Casual"],
  },
  {
    id: "2",
    name: "Denim Jacket",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "Men",
    category: "Jackets",
    color: "Blue",
    description:
      "A durable denim jacket with a classic blue wash. Ideal for layering and casual outings.",
    isFavorite: false,
    rating: { stars: 3.9, reviews: 136 },
    stock: {
      S: 15,
      M: 20,
      L: 25,
      XL: 10,
    },
    fitsWith: ["T-shirts", "Hoodies", "Pants"],
    style: ["Casual", "Streetwear"],
  },
  {
    id: "3",
    name: "Chic Blouse",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "Women",
    category: "Blouses",
    color: "White",
    description:
      "An elegant blouse with a clean and polished design. Available in a bright white shade, suitable for both professional and casual settings.",
    isFavorite: false,
    rating: { stars: 4.5, reviews: 412 },
    stock: {
      S: 10,
      M: 15,
      L: 5,
      XL: 8,
    },
    fitsWith: ["Skirts", "Pants"],
    style: ["Formal", "Elegant"],
  },
  {
    id: "4",
    name: "Cargo Pants",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "Unisex",
    category: "Pants",
    color: "Green",
    description:
      "Rugged and functional cargo pants made with durable materials, featuring multiple pockets for added utility. Available in green.",
    isFavorite: false,
    rating: { stars: 3.4, reviews: 89 },
    stock: {
      S: 10,
      M: 10,
      L: 5,
      XL: 0,
    },
    fitsWith: ["T-shirts", "Hoodies"],
    style: ["Casual", "Utility"],
  },
  {
    id: "5",
    name: "Running Sneakers",
    image: "src/assets/logo.png",
    priceCents: 10999,
    gender: "Men",
    category: "Shoes",
    color: "Black",
    description:
      "High-performance running sneakers with lightweight cushioning and excellent grip. Available in sleek black.",
    isFavorite: false,
    rating: { stars: 5.0, reviews: 952 },
    stock: {
      32: 5,
      34: 10,
      36: 8,
      38: 7,
      40: 0,
    },
    fitsWith: ["Shorts", "Hoodies"],
    style: ["Sporty"],
  },
  {
    id: "6",
    name: "Leather Boots",
    image: "src/assets/logo.png",
    priceCents: 8999,
    gender: "Women",
    category: "Shoes",
    color: "Brown",
    description:
      "Sophisticated leather boots crafted for both comfort and style. Available in a rich brown tone.",
    isFavorite: false,
    rating: { stars: 4.0, reviews: 220 },
    stock: {
      32: 3,
      34: 5,
      36: 2,
      38: 0,
      40: 5,
    },
    fitsWith: ["Skirts", "Dresses"],
    style: ["Elegant", "Chic"],
  },
  {
    id: "7",
    name: "Casual Dress",
    image: "src/assets/logo.png",
    priceCents: 5499,
    gender: "Women",
    category: "Dresses",
    color: "Pink",
    description:
      "A relaxed-fit casual dress in a solid pink shade, perfect for summer outings and casual gatherings.",
    isFavorite: false,
    rating: { stars: 3.7, reviews: 134 },
    stock: {
      S: 5,
      M: 4,
      L: 2,
      XL: 1,
    },
    fitsWith: ["Sandals"],
    style: ["Casual"],
  },
  {
    id: "8",
    name: "Sports Shorts",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "Unisex",
    category: "Shorts",
    color: "Grey",
    description:
      "Comfortable and breathable sports shorts designed for maximum mobility. Available in a neutral grey shade.",
    isFavorite: false,
    rating: { stars: 4.6, reviews: 303 },
    stock: {
      S: 10,
      M: 15,
      L: 10,
      XL: 5,
    },
    fitsWith: ["T-shirts", "Sneakers"],
    style: ["Sporty"],
  },
  {
    id: "9",
    name: "Wool Sweater",
    image: "src/assets/logo.png",
    priceCents: 5999,
    gender: "Men",
    category: "Sweaters",
    color: "Navy",
    description:
      "A cozy and warm wool sweater, crafted for chilly days. Comes in a deep navy blue shade.",
    isFavorite: false,
    rating: { stars: 3.8, reviews: 98 },
    stock: {
      S: 5,
      M: 8,
      L: 5,
      XL: 0,
    },
    fitsWith: ["Pants", "Jackets"],
    style: ["Casual", "Warm"],
  },
  {
    id: "10",
    name: "Formal Shirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "Men",
    category: "Shirts",
    color: "White",
    description:
      "A crisp and elegant formal shirt made from high-quality fabric. Available in classic white for professional occasions.",
    isFavorite: false,
    rating: { stars: 4.0, reviews: 179 },
    stock: {
      S: 10,
      M: 8,
      L: 4,
      XL: 0,
    },
    fitsWith: ["Pants", "Jackets"],
    style: ["Formal", "Office"],
  },
  {
    id: "11",
    name: "Summer Sandals",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "Women",
    category: "Shoes",
    color: "Pink",
    description:
      "Lightweight and breathable sandals with a focus on comfort. Available in a soft pink shade.",
    isFavorite: false,
    rating: { stars: 2.8, reviews: 65 },
    stock: {
      "One Size": 0,
    },
    fitsWith: ["Dresses", "Cover-ups"],
    style: ["Casual"],
  },
  {
    id: "12",
    name: "Track Jacket",
    image: "src/assets/logo.png",
    priceCents: 4499,
    gender: "Unisex",
    category: "Jackets",
    color: "Black",
    description:
      "A modern track jacket with a sleek design and functional features. Available in black.",
    isFavorite: false,
    rating: { stars: 4.1, reviews: 312 },
    stock: {
      S: 5,
      M: 5,
      L: 3,
      XL: 2,
    },
    fitsWith: ["Shorts", "Sweatpants"],
    style: ["Sporty"],
  },
  {
    id: "13",
    name: "Jeans",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "Unisex",
    category: "Pants",
    color: "Blue",
    description:
      "Classic straight-cut jeans made from durable denim. Ideal for casual and everyday wear, available in a traditional blue wash.",
    isFavorite: false,
    rating: { stars: 4.5, reviews: 438 },
    stock: {
      S: 0,
      M: 10,
      L: 8,
      XL: 2,
    },
    fitsWith: ["T-shirts", "Jackets"],
    style: ["Casual", "Streetwear"],
  },
  {
    id: "14",
    name: "Graphic Hoodie",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "Unisex",
    category: "Hoodies",
    color: "Grey",
    description:
      "A comfortable hoodie with a bold graphic design. Made from soft fabric for casual wear, available in grey.",
    isFavorite: false,
    rating: { stars: 3.1, reviews: 87 },
    stock: {
      S: 10,
      M: 10,
      L: 5,
      XL: 5,
    },
    fitsWith: ["Jeans", "Cargo Pants"],
    style: ["Casual", "Streetwear"],
  },
  {
    id: "15",
    name: "Sweatpants",
    image: "src/assets/logo.png",
    priceCents: 3499,
    gender: "Unisex",
    category: "Pants",
    color: "Black",
    description:
      "Comfortable and relaxed-fit sweatpants made for lounging or workouts. Available in classic black.",
    isFavorite: false,
    rating: { stars: 4.8, reviews: 362 },
    stock: {
      S: 8,
      M: 10,
      L: 5,
      XL: 2,
    },
    fitsWith: ["Hoodies", "Sneakers"],
    style: ["Casual", "Sporty"],
  },
  {
    id: "16",
    name: "Beach Cover-Up",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "Women",
    category: "Cover-ups",
    color: "Cyan",
    description:
      "A lightweight and breezy cover-up, ideal for beach outings. Comes in a refreshing cyan color.",
    isFavorite: false,
    rating: { stars: 2.9, reviews: 52 },
    stock: {
      "One Size": 15,
    },
    fitsWith: ["Swimwear", "Sandals"],
    style: ["Casual"],
  },
  {
    id: "17",
    name: "Polo Shirt",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "Men",
    category: "Shirts",
    color: "Green",
    description:
      "A classic polo shirt with a timeless design, made from soft and breathable fabric. Available in a rich green shade.",
    isFavorite: false,
    rating: { stars: 3.7, reviews: 144 },
    stock: {
      S: 10,
      M: 8,
      L: 2,
      XL: 0,
    },
    fitsWith: ["Jeans", "Jackets"],
    style: ["Smart Casual"],
  },
  {
    id: "18",
    name: "Maxi Skirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "Women",
    category: "Skirts",
    color: "Purple",
    description:
      "A flowy maxi skirt designed for comfort and style. Available in a soft purple shade, perfect for casual or semi-formal occasions.",
    isFavorite: false,
    rating: { stars: 4.1, reviews: 209 },
    stock: {
      S: 5,
      M: 4,
      L: 2,
      XL: 1,
    },
    fitsWith: ["Blouses", "Boots"],
    style: ["Chic", "Elegant"],
  },
  {
    id: "19",
    name: "Lightweight Jacket",
    image: "src/assets/logo.png",
    priceCents: 5999,
    gender: "Unisex",
    category: "Jackets",
    color: "Olive",
    description:
      "A lightweight and stylish jacket, perfect for transitional weather. Available in a versatile olive green shade.",
    isFavorite: false,
    rating: { stars: 4.7, reviews: 391 },
    stock: {
      S: 10,
      M: 5,
      L: 3,
      XL: 2,
    },
    fitsWith: ["Sweaters", "Pants"],
    style: ["Casual", "Outdoor"],
  },
  {
    id: "20",
    name: "Swim Trunks",
    image: "src/assets/logo.png",
    priceCents: 1999,
    gender: "Men",
    category: "Swimwear",
    color: "Yellow",
    description:
      "Vibrant swim trunks with a comfortable fit and quick-dry fabric. Available in sunny yellow.",
    isFavorite: false,
    rating: { stars: 3.3, reviews: 75 },
    stock: {
      S: 10,
      M: 8,
      L: 6,
      XL: 4,
    },
    fitsWith: ["Cover-ups", "Sandals"],
    style: ["Beach"],
  },
];

console.log(clothes.length);
