import { nanoid } from "nanoid";

export const clothes = [
  {
    id: nanoid(),
    name: "Classic T-Shirt",
    image: "src/assets/logo.png",
    priceCents: 1999,
    gender: "unisex",
    category: "T-shirts",
    color: ["red", "black"],
    stock: 50,
    description:
      "A comfortable classic t-shirt available in red and black for everyday wear.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Denim Jacket",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "male",
    category: "Jackets",
    color: ["blue", "black"],
    stock: 20,
    description:
      "A stylish denim jacket perfect for layering, available in blue and black.",
    isNew: false,
    rating: 3.9,
  },
  {
    id: nanoid(),
    name: "Chic Blouse",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "female",
    category: "Blouses",
    color: ["white", "pink"],
    stock: 15,
    description:
      "A chic blouse available in white and pink for a polished look.",
    isNew: false,
    rating: 4.5,
  },
  {
    id: nanoid(),
    name: "Cargo Pants",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "unisex",
    category: "Pants",
    color: "green",
    stock: 25,
    description: "Durable cargo pants with multiple pockets.",
    isNew: false,
    rating: 3.4,
  },
  {
    id: nanoid(),
    name: "Running Sneakers",
    image: "src/assets/logo.png",
    priceCents: 6999,
    gender: "unisex",
    category: "Shoes",
    color: ["black", "white"],
    stock: 30,
    description:
      "Lightweight running sneakers for optimal performance, available in black and white.",
    isNew: false,
    rating: 5.0,
  },
  {
    id: nanoid(),
    name: "Leather Boots",
    image: "src/assets/logo.png",
    priceCents: 8999,
    gender: "female",
    category: "Shoes",
    color: "brown",
    stock: 10,
    description: "Stylish leather boots for any occasion.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "Casual Dress",
    image: "src/assets/logo.png",
    priceCents: 5499,
    gender: "female",
    category: "Dresses",
    color: ["floral", "pink"],
    stock: 12,
    description: "A casual dress available in floral pattern and solid pink.",
    isNew: false,
    rating: 3.7,
  },
  {
    id: nanoid(),
    name: "Sports Shorts",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "unisex",
    category: "Shorts",
    color: ["grey", "black"],
    stock: 40,
    description:
      "Comfortable sports shorts available in grey and black for all your activities.",
    isNew: false,
    rating: 4.6,
  },
  {
    id: nanoid(),
    name: "Wool Sweater",
    image: "src/assets/logo.png",
    priceCents: 5999,
    gender: "male",
    category: "Sweaters",
    color: "navy",
    stock: 18,
    description: "A cozy wool sweater to keep you warm.",
    isNew: false,
    rating: 3.8,
  },
  {
    id: nanoid(),
    name: "Formal Shirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "male",
    category: "Shirts",
    color: ["white", "blue"],
    stock: 22,
    description:
      "A crisp formal shirt available in white and blue for special occasions.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "Summer Sandals",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "female",
    category: "Shoes",
    color: "pink",
    stock: 0,
    description: "Comfortable sandals perfect for summer days.",
    isNew: false,
    rating: 2.8,
  },
  {
    id: nanoid(),
    name: "Track Jacket",
    image: "src/assets/logo.png",
    priceCents: 4499,
    gender: "unisex",
    category: "Jackets",
    color: "black",
    stock: 15,
    description: "A stylish track jacket for sports and leisure.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Jeans",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "unisex",
    category: "Pants",
    color: "blue",
    stock: 0,
    description: "Classic blue jeans for casual wear.",
    isNew: false,
    rating: 4.5,
  },
  {
    id: nanoid(),
    name: "Graphic Hoodie",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "unisex",
    category: "Hoodies",
    color: ["grey", "navy"],
    stock: 30,
    description:
      "A cozy hoodie with a fun graphic design, available in grey and navy.",
    isNew: false,
    rating: 3.1,
  },
  {
    id: nanoid(),
    name: "Sweatpants",
    image: "src/assets/logo.png",
    priceCents: 3499,
    gender: "unisex",
    category: "Pants",
    color: ["black", "grey"],
    stock: 25,
    description:
      "Comfortable sweatpants available in black and grey for lounging or workouts.",
    isNew: false,
    rating: 4.8,
  },
  {
    id: nanoid(),
    name: "Beach Cover-Up",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "female",
    category: "Cover-ups",
    color: "cyan",
    stock: 15,
    description: "Light and breezy cover-up for beach days.",
    isNew: false,
    rating: 2.9,
  },
  {
    id: nanoid(),
    name: "Polo Shirt",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "male",
    category: "Shirts",
    color: ["green", "navy"],
    stock: 20,
    description:
      "A classic polo shirt available in green and navy for smart casual looks.",
    isNew: false,
    rating: 3.7,
  },
  {
    id: nanoid(),
    name: "Maxi Skirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "female",
    category: "Skirts",
    color: "purple",
    stock: 12,
    description: "Flowy maxi skirt for a feminine touch.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Lightweight Jacket",
    image: "src/assets/logo.png",
    priceCents: 5999,
    gender: "unisex",
    category: "Jackets",
    color: "olive",
    stock: 20,
    description:
      "Perfect for transitional weather, this jacket is lightweight and stylish.",
    isNew: false,
    rating: 4.7,
  },
  {
    id: nanoid(),
    name: "Bikini Set",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "female",
    category: "Swimwear",
    color: "red",
    stock: 18,
    description: "A stylish bikini set for beach outings.",
    isNew: false,
    rating: 3.2,
  },
  {
    id: nanoid(),
    name: "Puffer Vest",
    image: "src/assets/logo.png",
    priceCents: 6999,
    gender: "unisex",
    category: "Vests",
    color: "black",
    stock: 10,
    description: "A warm puffer vest for chilly days.",
    isNew: false,
    rating: 3.8,
  },
  {
    id: nanoid(),
    name: "Cardigan",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "female",
    category: "Sweaters",
    color: "beige",
    stock: 25,
    description: "A cozy cardigan to layer up your outfit.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "Swim Trunks",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "male",
    category: "Swimwear",
    color: "blue",
    stock: 0,
    description: "Quick-dry swim trunks for pool or beach.",
    isNew: false,
    rating: 3.8,
  },
  {
    id: nanoid(),
    name: "Thermal Top",
    image: "src/assets/logo.png",
    priceCents: 3499,
    gender: "unisex",
    category: "T-shirts",
    color: ["black", "grey"],
    stock: 22,
    description:
      "A warm thermal top for cold weather, available in black and dark grey.",
    isNew: false,
    rating: 4.3,
  },
  {
    id: nanoid(),
    name: "Flannel Shirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "male",
    category: "Shirts",
    color: ["red", "blue"],
    stock: 18,
    description:
      "A comfortable flannel shirt available in red and blue plaid for casual wear.",
    isNew: false,
    rating: 3.7,
  },
  {
    id: nanoid(),
    name: "Activewear Leggings",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "female",
    category: "Pants",
    color: ["black", "blue"],
    stock: 25,
    description:
      "High-performance leggings available in black and dark blue for your workouts.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Winter Coat",
    image: "src/assets/logo.png",
    priceCents: 12999,
    gender: "unisex",
    category: "Coats",
    color: ["black", "navy"],
    stock: 8,
    description:
      "A heavy-duty winter coat for extreme weather, available in black and navy.",
    isNew: false,
    rating: 5.0,
  },
  {
    id: nanoid(),
    name: "Gym Backpack",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "unisex",
    category: "Accessories",
    color: ["red", "blue"],
    stock: 20,
    description:
      "A spacious backpack available in red and blue for gym and daily use.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Ski Jacket",
    image: "src/assets/logo.png",
    priceCents: 14999,
    gender: "unisex",
    category: "Coats",
    color: "white",
    stock: 10,
    description: "Insulated ski jacket to keep you warm on the slopes.",
    isNew: false,
    rating: 4.9,
  },
  {
    id: nanoid(),
    name: "Smartwatch",
    image: "src/assets/logo.png",
    priceCents: 7999,
    gender: "unisex",
    category: "Accessories",
    color: "black",
    stock: 15,
    description:
      "A sleek smartwatch to track your fitness and keep you connected.",
    isNew: true,
    rating: 4.6,
  },
  {
    id: nanoid(),
    name: "Cashmere Scarf",
    image: "src/assets/logo.png",
    priceCents: 6999,
    gender: "unisex",
    category: "Accessories",
    color: "grey",
    stock: 20,
    description: "A soft cashmere scarf for extra warmth and style.",
    isNew: false,
    rating: 4.5,
  },
  {
    id: nanoid(),
    name: "Sun Hat",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "female",
    category: "Accessories",
    color: "beige",
    stock: 30,
    description: "A stylish sun hat for sunny days.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "Leather Wallet",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "unisex",
    category: "Accessories",
    color: "brown",
    stock: 50,
    description: "A classic leather wallet to keep your essentials safe.",
    isNew: false,
    rating: 4.2,
  },
  {
    id: nanoid(),
    name: "Track Pants",
    image: "src/assets/logo.png",
    priceCents: 3499,
    gender: "unisex",
    category: "Pants",
    color: "navy",
    stock: 30,
    description: "Comfortable track pants for lounging and casual outings.",
    isNew: false,
    rating: 4.3,
  },
  {
    id: nanoid(),
    name: "Yoga Mat",
    image: "src/assets/logo.png",
    priceCents: 1999,
    gender: "unisex",
    category: "Accessories",
    color: "purple",
    stock: 40,
    description: "A high-quality yoga mat for all your fitness routines.",
    isNew: false,
    rating: 4.6,
  },
  {
    id: nanoid(),
    name: "Windbreaker Jacket",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "unisex",
    category: "Jackets",
    color: "yellow",
    stock: 25,
    description: "A lightweight windbreaker jacket perfect for active days.",
    isNew: false,
    rating: 4.2,
  },
  {
    id: nanoid(),
    name: "Linen Shirt",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "male",
    category: "Shirts",
    color: "white",
    stock: 15,
    description: "A breathable linen shirt for summer days.",
    isNew: false,
    rating: 4.4,
  },
  {
    id: nanoid(),
    name: "Trench Coat",
    image: "src/assets/logo.png",
    priceCents: 7999,
    gender: "female",
    category: "Coats",
    color: "beige",
    stock: 0,
    description: "A classic trench coat for all seasons.",
    isNew: false,
    rating: 4.8,
  },
  {
    id: nanoid(),
    name: "Hiking Boots",
    image: "src/assets/logo.png",
    priceCents: 8999,
    gender: "unisex",
    category: "Shoes",
    color: "brown",
    stock: 30,
    description: "Durable hiking boots for outdoor adventures.",
    isNew: true,
    rating: 4.7,
  },
  {
    id: nanoid(),
    name: "Biker Jacket",
    image: "src/assets/logo.png",
    priceCents: 6999,
    gender: "male",
    category: "Jackets",
    color: "black",
    stock: 12,
    description: "A bold biker jacket for an edgy look.",
    isNew: false,
    rating: 4.5,
  },
  {
    id: nanoid(),
    name: "Pink Skirt",
    image: "src/assets/logo.png",
    priceCents: 3599,
    gender: "female",
    category: "Skirts",
    color: "pink",
    stock: 20,
    description: "A beautiful floral skirt for a fresh look.",
    isNew: false,
    rating: 3.9,
  },
  {
    id: nanoid(),
    name: "Work Boots",
    image: "src/assets/logo.png",
    priceCents: 7999,
    gender: "unisex",
    category: "Shoes",
    color: "black",
    stock: 10,
    description: "Sturdy boots designed for heavy-duty work environments.",
    isNew: true,
    rating: 4.6,
  },
  {
    id: nanoid(),
    name: "Hooded Sweatshirt",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "unisex",
    category: "Hoodies",
    color: "red",
    stock: 45,
    description: "A comfortable hooded sweatshirt for all-day wear.",
    isNew: true,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Pullover Sweater",
    image: "src/assets/logo.png",
    priceCents: 4599,
    gender: "female",
    category: "Sweaters",
    color: "cyan",
    stock: 22,
    description: "A cozy pullover sweater for colder days.",
    isNew: false,
    rating: 4.3,
  },
  {
    id: nanoid(),
    name: "Chinos",
    image: "src/assets/logo.png",
    priceCents: 4499,
    gender: "male",
    category: "Pants",
    color: "khaki",
    stock: 40,
    description: "Comfortable chinos for a smart-casual look.",
    isNew: false,
    rating: 4.4,
  },
  {
    id: nanoid(),
    name: "Fleece Jacket",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "unisex",
    category: "Jackets",
    color: "grey",
    stock: 20,
    description: "A cozy fleece jacket for outdoor activities.",
    isNew: true,
    rating: 4.2,
  },
  {
    id: nanoid(),
    name: "Polo Dress",
    image: "src/assets/logo.png",
    priceCents: 3999,
    gender: "female",
    category: "Dresses",
    color: "navy",
    stock: 15,
    description: "A casual yet elegant polo dress.",
    isNew: true,
    rating: 4.5,
  },
  {
    id: nanoid(),
    name: "Canvas Sneakers",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "unisex",
    category: "Shoes",
    color: "white",
    stock: 50,
    description: "Classic canvas sneakers for casual wear.",
    isNew: false,
    rating: 4.1,
  },
  {
    id: nanoid(),
    name: "Ballet Flats",
    image: "src/assets/logo.png",
    priceCents: 2499,
    gender: "female",
    category: "Shoes",
    color: "black",
    stock: 30,
    description: "Elegant ballet flats for a chic look.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "Windbreaker Pants",
    image: "src/assets/logo.png",
    priceCents: 3499,
    gender: "unisex",
    category: "Pants",
    color: "blue",
    stock: 35,
    description: "Lightweight windbreaker pants for active wear.",
    isNew: false,
    rating: 4.3,
  },
  {
    id: nanoid(),
    name: "Knit Beanie",
    image: "src/assets/logo.png",
    priceCents: 1499,
    gender: "unisex",
    category: "Accessories",
    color: "grey",
    stock: 0,
    description: "A cozy knit beanie for winter warmth.",
    isNew: true,
    rating: 4.2,
  },
  {
    id: nanoid(),
    name: "Faux Fur Coat",
    image: "src/assets/logo.png",
    priceCents: 10999,
    gender: "female",
    category: "Coats",
    color: "white",
    stock: 10,
    description: "A luxurious faux fur coat for winter occasions.",
    isNew: false,
    rating: 4.8,
  },
  {
    id: nanoid(),
    name: "Puffer Jacket",
    image: "src/assets/logo.png",
    priceCents: 7999,
    gender: "unisex",
    category: "Coats",
    color: "black",
    stock: 18,
    description: "A warm puffer jacket for cold weather protection.",
    isNew: false,
    rating: 4.9,
  },
  {
    id: nanoid(),
    name: "Raincoat",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "unisex",
    category: "Coats",
    color: "yellow",
    stock: 0,
    description: "A stylish raincoat for rainy days.",
    isNew: false,
    rating: 4.0,
  },
  {
    id: nanoid(),
    name: "V-neck Sweater",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "male",
    category: "Sweaters",
    color: "green",
    stock: 40,
    description: "A cozy V-neck sweater for layering.",
    isNew: true,
    rating: 4.3,
  },
  {
    id: nanoid(),
    name: "Straw Hat",
    image: "src/assets/logo.png",
    priceCents: 2999,
    gender: "female",
    category: "Accessories",
    color: "beige",
    stock: 50,
    description: "A chic straw hat for sunny days.",
    isNew: false,
    rating: 4.6,
  },
  {
    id: nanoid(),
    name: "Summer Dress",
    image: "src/assets/logo.png",
    priceCents: 4999,
    gender: "female",
    category: "Dresses",
    color: "white",
    stock: 35,
    description: "A light and airy summer dress.",
    isNew: false,
    rating: 4.5,
  },
];

console.log(clothes.length);
